/** Medical Academy — training, intake and formation. */
export const MEDICAL_ACADEMY_DEPARTMENT_SLUG = 'medical-academy';
export const MEDICAL_ACADEMY_DEPARTMENT_NAME = 'Medical Academy';
export const MEDICAL_ACADEMY_DEPARTMENT_ABBREVIATION = 'MA';

/** @deprecated Use MEDICAL_ACADEMY_DEPARTMENT_SLUG */
export const RTD_DEPARTMENT_SLUG = MEDICAL_ACADEMY_DEPARTMENT_SLUG;
/** @deprecated Use MEDICAL_ACADEMY_DEPARTMENT_NAME */
export const RTD_DEPARTMENT_NAME = MEDICAL_ACADEMY_DEPARTMENT_NAME;
/** @deprecated Use MEDICAL_ACADEMY_DEPARTMENT_ABBREVIATION */
export const RTD_DEPARTMENT_ABBREVIATION = MEDICAL_ACADEMY_DEPARTMENT_ABBREVIATION;
